"""Added FuelLog model

Revision ID: 31fc8e3cea52
Revises: ac6fc843225b
Create Date: 2026-02-21 09:41:24.972558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fc8e3cea52'
down_revision = 'ac6fc843225b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_logs',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('liters', sa.Float(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fuel_logs')
    # ### end Alembic commands ###
