"""Upgraded vehicle schema to match wireframe

Revision ID: 39891624d406
Revises: 31fc8e3cea52
Create Date: 2026-02-21 11:26:25.256710

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39891624d406'
down_revision = '31fc8e3cea52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type', sa.Enum('TRUCK', 'VAN', 'BIKE', name='vehicletype'), nullable=False))
        batch_op.add_column(sa.Column('model', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('year')
        batch_op.drop_column('model')
        batch_op.drop_column('vehicle_type')

    # ### end Alembic commands ###
