"""Added remarks to maintenance

Revision ID: 7654d4421f7a
Revises: 39891624d406
Create Date: 2026-02-21 12:25:57.575934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7654d4421f7a'
down_revision = '39891624d406'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
