"""Initial models

Revision ID: edbf6c08ccea
Revises: 
Create Date: 2026-02-21 09:31:42.965129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbf6c08ccea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('license_category', sa.String(length=50), nullable=False),
    sa.Column('license_expiry_date', sa.Date(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('ON_DUTY', 'ON_TRIP', 'OFF_DUTY', 'SUSPENDED', name='driverstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'DISPATCHER', 'SAFETY_OFFICER', 'ANALYST', name='userrole'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=50), nullable=False),
    sa.Column('max_capacity', sa.Float(), nullable=False),
    sa.Column('odometer', sa.Float(), nullable=True),
    sa.Column('acquisition_cost', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'ON_TRIP', 'IN_SHOP', 'RETIRED', name='vehiclestatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_table('drivers')
    # ### end Alembic commands ###
